# Generated by Django 4.2.5 on 2023-09-20 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_game_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('started', 'GAME STARTED'), ('waiting', 'WAITING'), ('created', 'CREATED'), ('finished', 'FINISHED')], default='created', max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
